/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JsonObject } from '../../models/json-object';

export interface CertificationQcmSubmit$Params {
  attempt: number;
      body: JsonObject
}

export function certificationQcmSubmit(http: HttpClient, rootUrl: string, params: CertificationQcmSubmit$Params, context?: HttpContext): Observable<StrictHttpResponse<JsonObject>> {
  const rb = new RequestBuilder(rootUrl, certificationQcmSubmit.PATH, 'post');
  if (params) {
    rb.path('attempt', params.attempt, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JsonObject>;
    })
  );
}

certificationQcmSubmit.PATH = '/contractor-compliance/certification/qcm/{attempt}/submit';
