/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DocumentsDownload$Params {
  uuid: string;

/**
 * Si `true`, force `Content-Disposition: inline` pour preview navigateur.
 */
  inline?: boolean;
}

export function documentsDownload(http: HttpClient, rootUrl: string, params: DocumentsDownload$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, documentsDownload.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.query('inline', params.inline, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

documentsDownload.PATH = '/contractor-compliance/documents/{uuid}/file';
