/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JsonObject } from '../../models/json-object';

export interface DocumentsList$Params {
  status?: string;
  type?: string;
  page?: number;
}

export function documentsList(http: HttpClient, rootUrl: string, params?: DocumentsList$Params, context?: HttpContext): Observable<StrictHttpResponse<JsonObject>> {
  const rb = new RequestBuilder(rootUrl, documentsList.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('type', params.type, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JsonObject>;
    })
  );
}

documentsList.PATH = '/contractor-compliance/documents';
