/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AdminAuthRequestPin$Params {
      body: {

/**
 * Email ou username staff (recherche permissive sur oauth_users).
 */
'email': string;
}
}

export function adminAuthRequestPin(http: HttpClient, rootUrl: string, params: AdminAuthRequestPin$Params, context?: HttpContext): Observable<StrictHttpResponse<{

/**
 * Token éphémère à passer en header `Sms-Trip` au signin.
 */
'sms_trip_token': string;

/**
 * Date d'expiration du PIN (format Y-m-d H:i:s).
 */
'expires_at': string;

/**
 * Canal de diffusion effectif du PIN (slack si dispo, log sinon).
 */
'pincode_media': 'log' | 'slack';
}>> {
  const rb = new RequestBuilder(rootUrl, adminAuthRequestPin.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      
      /**
       * Token éphémère à passer en header `Sms-Trip` au signin.
       */
      'sms_trip_token': string;
      
      /**
       * Date d'expiration du PIN (format Y-m-d H:i:s).
       */
      'expires_at': string;
      
      /**
       * Canal de diffusion effectif du PIN (slack si dispo, log sinon).
       */
      'pincode_media': 'log' | 'slack';
      }>;
    })
  );
}

adminAuthRequestPin.PATH = '/contractor-compliance/admin/auth/request-pin';
