/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JsonObject } from '../../models/json-object';

export interface AdminWebhooksReplay$Params {
  id: number;
}

export function adminWebhooksReplay(http: HttpClient, rootUrl: string, params: AdminWebhooksReplay$Params, context?: HttpContext): Observable<StrictHttpResponse<JsonObject>> {
  const rb = new RequestBuilder(rootUrl, adminWebhooksReplay.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JsonObject>;
    })
  );
}

adminWebhooksReplay.PATH = '/contractor-compliance/admin/webhooks/{id}/replay';
