/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AdminKycArtifactsView$Params {
  uuid: string;

/**
 * Chemin relatif de l'artifact KYC à streamer (.webm, .jpg…).
 */
  path: string;
}

export function adminKycArtifactsView(http: HttpClient, rootUrl: string, params: AdminKycArtifactsView$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, adminKycArtifactsView.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.query('path', params.path, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

adminKycArtifactsView.PATH = '/contractor-compliance/admin/kyc/{uuid}/artifacts/view';
