/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminContractorsKycSessions$Params {

/**
 * Identifiant contractor format `P<digits>` (Tuita phone-keyed).
 */
  phone: string;
  page?: number;
  per_page?: number;
  search?: string;
  status?: string;
  type?: string;
  document_type?: string;

/**
 * Si `true`, ne renvoie que les éléments sans facture associée.
 */
  without_invoice?: boolean;
  sort?: string;

/**
 * Sens de tri des sous-listes admin (param `dir`, distinct de `direction`).
 */
  dir?: 'asc' | 'desc';

/**
 * Inclut les anciennes versions de documents (re-uploads, renouvellements).
 */
  include_old_versions?: boolean;
}

export function adminContractorsKycSessions(http: HttpClient, rootUrl: string, params: AdminContractorsKycSessions$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminContractorsKycSessions.PATH, 'get');
  if (params) {
    rb.path('phone', params.phone, {});
    rb.query('page', params.page, {});
    rb.query('per_page', params.per_page, {});
    rb.query('search', params.search, {});
    rb.query('status', params.status, {});
    rb.query('type', params.type, {});
    rb.query('document_type', params.document_type, {});
    rb.query('without_invoice', params.without_invoice, {});
    rb.query('sort', params.sort, {});
    rb.query('dir', params.dir, {});
    rb.query('include_old_versions', params.include_old_versions, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminContractorsKycSessions.PATH = '/contractor-compliance/admin/contractors/{phone}/kyc-sessions';
