/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JsonObject } from '../../models/json-object';

export interface AdminContractorsPurchases$Params {

/**
 * Identifiant contractor format `P<digits>` (Tuita phone-keyed).
 */
  phone: string;
}

export function adminContractorsPurchases(http: HttpClient, rootUrl: string, params: AdminContractorsPurchases$Params, context?: HttpContext): Observable<StrictHttpResponse<JsonObject>> {
  const rb = new RequestBuilder(rootUrl, adminContractorsPurchases.PATH, 'get');
  if (params) {
    rb.path('phone', params.phone, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JsonObject>;
    })
  );
}

adminContractorsPurchases.PATH = '/contractor-compliance/admin/contractors/{phone}/purchases';
