/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminContractorsList$Params {
  page?: number;
  per_page?: number;
  search?: string;
  status?: string;
  sort?: string;
  direction?: 'asc' | 'desc';

/**
 * Recherche libre (nom / email / phone — appliquée côté repository).
 */
  q?: string;

/**
 * Filtre exact sur le téléphone (`cc_users.phone`).
 */
  phone?: string;

/**
 * Filtre exact sur l'email (`cc_users.email`).
 */
  email?: string;

/**
 * Ordre de tri (le controller lit `order`, pas `direction`).
 * Défaut backend `desc`.
 */
  order?: 'asc' | 'desc';
}

export function adminContractorsList(http: HttpClient, rootUrl: string, params?: AdminContractorsList$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminContractorsList.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('per_page', params.per_page, {});
    rb.query('search', params.search, {});
    rb.query('status', params.status, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
    rb.query('q', params.q, {});
    rb.query('phone', params.phone, {});
    rb.query('email', params.email, {});
    rb.query('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminContractorsList.PATH = '/contractor-compliance/admin/contractors';
