/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JsonObject } from '../../models/json-object';

export interface AdminInvitationCodesList$Params {
  status?: string;
  per_page?: number;
  page?: number;
  sort?: string;
  direction?: 'asc' | 'desc';
}

export function adminInvitationCodesList(http: HttpClient, rootUrl: string, params?: AdminInvitationCodesList$Params, context?: HttpContext): Observable<StrictHttpResponse<JsonObject>> {
  const rb = new RequestBuilder(rootUrl, adminInvitationCodesList.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('per_page', params.per_page, {});
    rb.query('page', params.page, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JsonObject>;
    })
  );
}

adminInvitationCodesList.PATH = '/contractor-compliance/admin/invitation-codes';
