/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminInvitationCodeCreateRequest } from '../../models/admin-invitation-code-create-request';
import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminInvitationCodesCreate$Params {
      body: AdminInvitationCodeCreateRequest
}

export function adminInvitationCodesCreate(http: HttpClient, rootUrl: string, params: AdminInvitationCodesCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminInvitationCodesCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminInvitationCodesCreate.PATH = '/contractor-compliance/admin/invitation-codes';
