/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminInvitationCodeCreateRequest {

  /**
   * Durée de validité en jours, lue par le backend (défaut 7,
   * bornée 1–365).
   */
  expires_in_days?: number;

  /**
   * Nombre maximal d'usages ; null = illimité.
   */
  max_uses?: number | null;

  /**
   * À qui le code est destiné (audit + heuristique mismatch).
   */
  note?: string | null;
}
