/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminInvitationCodeCreateRequest {

  /**
   * Durée de validité en jours, lue par le backend (défaut 7,
   * bornée 1–365).
   */
  expires_in_days?: number;

  /**
   * Qui crée le code (email/nom Tuita). Obligatoire — le backend
   * rejette la création avec VALIDATION_FAILED
   * « generated_by_label est obligatoire » si le champ est vide.
   */
  generated_by_label: string;

  /**
   * Nombre maximal d'usages ; null = illimité.
   */
  max_uses?: number | null;

  /**
   * À qui le code est destiné (audit + heuristique mismatch).
   */
  note?: string | null;
}
