/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminFreeInvoiceApproveRequest {

  /**
   * Note interne admin (facultative), tracée dans l'audit.
   */
  note?: string;

  /**
   * Durée de validité de l'autorisation en heures (défaut 24).
   */
  ttl_hours?: number;
}
