/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiError {

  /**
   * Code machine-readable (ex: INVITATION_CODE_NOT_FOUND). Stable, utilisé par le frontend pour brancher la logique.
   */
  code: string;

  /**
   * Détails optionnels (ex: champ en faute, contexte). Format libre par endpoint.
   */
  details?: {
[key: string]: any;
};

  /**
   * Message en français, prêt à afficher à l'utilisateur final tel quel.
   */
  message: string;
}
