/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CertificationHeartbeatRequest {

  /**
   * UUID de la tentative QCM active à prolonger.
   */
  attempt_uuid: string;
}
