/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CertificationAnswersRequest {

  /**
   * Réponses du QCM indexées par numéro de question (1..24) → A/B/C.
   * Complètes pour /complete, partielles autorisées pour /answers.
   */
  answers: {
[key: string]: string;
};

  /**
   * UUID de la tentative QCM.
   */
  attempt_uuid: string;
}
