/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContractorMission } from '../models/contractor-mission';
import { MissionsMeta } from '../models/missions-meta';
export interface ContractorMissionListResponse {
  data: Array<ContractorMission>;
  meta: MissionsMeta;
}
