/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvoiceStatusFront } from '../models/invoice-status-front';
export interface ContractorMission {

  /**
   * Ce contractor peut-il piloter la mission (master vs secondary).
   */
  canRun: boolean;

  /**
   * Référence dossier (CMD-XXX / opportunity caseNumber).
   */
  caseNumber: string;
  city?: string | null;

  /**
   * Numéro de facture contractor si présent.
   */
  invoice_number?: string | null;
  invoice_status: InvoiceStatusFront;
  invoice_uuid?: string | null;

  /**
   * ID Tuita de la MissionStatement (= primary key affichable).
   */
  mid: string;
  missionTitle: string;

  /**
   * Identifiant unique court côté contractor (cm.mission_uid).
   */
  missionUid?: string | null;

  /**
   * Alias snake_case de caseNumber (rétrocompat admin).
   */
  mission_ref?: string;

  /**
   * Clé technique : ridge, gutter, previsit, starlink, etc.
   */
  operationType: string;

  /**
   * Libellé humain (lookup ValueRegistry ROOFING_OPERATION_TYPE).
   */
  operationTypeLabel: string;

  /**
   * Prix contractor en € (depuis cft_smith_contract.price, round 2).
   */
  price: number;

  /**
   * ISO 8601, date de signature de la mission (réalisée si non-null).
   */
  signedAt?: string | null;

  /**
   * Adresse VAGUE (postal_code + city). Pas la rue / numéro
   * (consigne business anti-court-circuit).
   */
  targetAddress?: string | null;
  visitDateConfirmed?: string | null;
}
