/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContractorMission } from '../models/contractor-mission';
export interface ContractorMissionDetailResponse {
  data: ContractorMission;
}
