/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FreeInvoiceRequestCreate {

  /**
   * Montant TTC en centimes (le front convertit les euros saisis).
   */
  amount_ttc_cents: number;

  /**
   * Nom du client (personne/société) que le contractor facture.
   */
  client_name: string;

  /**
   * Description de la prestation facturée.
   */
  description: string;

  /**
   * Justificatifs joints à la demande (PDF/JPG/PNG/WEBP, 20 Mo max chacun, 10 maximum). Au moins 1 obligatoire.
   */
  justificatifs: Array<Blob>;

  /**
   * Références de missions Tuita associées (optionnel).
   */
  mission_refs?: Array<string>;
}
