/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 9 statuts de facture exposés au front contractor. Mapping interne
 * 14 statuts -> 9 réalisé dans InvoiceStatusMapper côté backend.
 */
export enum InvoiceStatusFront {
  NONE = 'none',
  VALIDATING = 'validating',
  PENDING_VALIDATION = 'pending_validation',
  READY_TO_PAY = 'ready_to_pay',
  PAYING = 'paying',
  PAID = 'paid',
  UPLOADED = 'uploaded',
  AUTO_GENERATED = 'auto_generated',
  REJECTED = 'rejected'
}
