/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Catégorie front (mapping depuis DxMission.missionType).
 */
export enum MissionOfferCategory {
  PRE_VISITE = 'pre_visite',
  FIBRE = 'fibre',
  BTP = 'btp',
  AUTRE = 'autre'
}
