/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MissionOffersMeta {

  /**
   * False quand le contractor n'est pas encore fully_verified.
   * Le front affiche les offres mais désactive accept/decline.
   */
  can_accept: boolean;
  last_page: number;
  links?: {
'self'?: string | null;
'first'?: string | null;
'last'?: string | null;
'next'?: string | null;
'prev'?: string | null;
};
  page: number;
  per_page: number;
  total: number;
}
