/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MissionOfferAddress {
  city: string;

  /**
   * Code département (2 chiffres) dérivé du postal_code.
   */
  department: string;
  postal_code: string;

  /**
   * Vide côté liste offres (consigne anti-court-circuit). La rue
   * n'est révélée qu'après acceptation effective sur une autre route.
   */
  street: string;
}
