/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MissionOfferAddress } from '../models/mission-offer-address';
import { MissionOfferCategory } from '../models/mission-offer-category';
export interface MissionOffer {
  address: MissionOfferAddress;
  category: MissionOfferCategory;
  description_short: string;

  /**
   * Montant TTC attendu en €.
   */
  expected_amount_ttc?: number | null;
  expires_at: string;

  /**
   * Référence mission (= DxMission.caseNumber).
   */
  mission_ref: string;
  offered_at: string;

  /**
   * Certifications requises pour accepter (vide pour l'instant côté Tuita).
   */
  required_badges: Array<string>;
  scheduled_at: string;
  title: string;
}
