/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MissionOffer } from '../models/mission-offer';
import { MissionOffersMeta } from '../models/mission-offers-meta';
export interface MissionOffersListResponse {
  data: Array<MissionOffer>;
  meta: MissionOffersMeta;
}
