/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MissionsMeta {

  /**
   * Total après filtres (= taille effective).
   */
  filtered_total: number;

  /**
   * Map { 'none' => N, 'paid' => N, ... } sur les 9 statuts front.
   */
  invoice_status_counts: {
[key: string]: number;
};
  last_page: number;
  links?: {
'self'?: string | null;
'first'?: string | null;
'last'?: string | null;
'next'?: string | null;
'prev'?: string | null;
};
  page: number;
  per_page: number;

  /**
   * Nombre de missions avec signedAt != null.
   */
  realized: number;

  /**
   * Missions réalisées dont l'invoice_status est none ou rejected
   * (= action upload facture requise côté Freemium).
   */
  realized_to_invoice: number;

  /**
   * Total brut (avant filtres).
   */
  total: number;
}
