/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SuccessEnvelope {

  /**
   * Payload métier — type variable selon l'endpoint.
   */
  data: any;

  /**
   * Métadonnées optionnelles (pagination, cursors, etc.).
   */
  meta?: {
[key: string]: any;
};
}
