/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JsonObject } from '../../models/json-object';

export interface MissionsActive$Params {
  status?: string;
  search?: string;
  invoice_status?: string;
  page?: number;
  per_page?: number;
}

export function missionsActive(http: HttpClient, rootUrl: string, params?: MissionsActive$Params, context?: HttpContext): Observable<StrictHttpResponse<JsonObject>> {
  const rb = new RequestBuilder(rootUrl, missionsActive.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('search', params.search, {});
    rb.query('invoice_status', params.invoice_status, {});
    rb.query('page', params.page, {});
    rb.query('per_page', params.per_page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JsonObject>;
    })
  );
}

missionsActive.PATH = '/contractor-compliance/missions/active';
