/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContractorMissionDetailResponse } from '../../models/contractor-mission-detail-response';

export interface MissionsShow$Params {
  ref: string;
}

export function missionsShow(http: HttpClient, rootUrl: string, params: MissionsShow$Params, context?: HttpContext): Observable<StrictHttpResponse<ContractorMissionDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, missionsShow.PATH, 'get');
  if (params) {
    rb.path('ref', params.ref, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContractorMissionDetailResponse>;
    })
  );
}

missionsShow.PATH = '/contractor-compliance/missions/{ref}';
