/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface InvitationCodesCheck$Params {

/**
 * Code d'invitation 4 caractères (alphabet `[A-HJ-NP-Z2-9]`).
 */
  code: string;
}

export function invitationCodesCheck(http: HttpClient, rootUrl: string, params: InvitationCodesCheck$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': {
'valid': boolean;

/**
 * Présent uniquement quand valid=false.
 */
'reason'?: 'invalid_format' | 'not_found' | 'revoked' | 'expired' | 'exhausted';
};
}>> {
  const rb = new RequestBuilder(rootUrl, invitationCodesCheck.PATH, 'get');
  if (params) {
    rb.query('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': {
      'valid': boolean;
      
      /**
       * Présent uniquement quand valid=false.
       */
      'reason'?: 'invalid_format' | 'not_found' | 'revoked' | 'expired' | 'exhausted';
      };
      }>;
    })
  );
}

invitationCodesCheck.PATH = '/contractor-compliance/invitation-codes/check';
