/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminInvoicesList$Params {
  search?: string;
  stuck?: boolean;
  page?: number;
  per_page?: number;
  sort?: string;
  direction?: 'asc' | 'desc';
  q?: string;

/**
 * Filtre multi-statuts (onglets). Sérialisé `status[]=a&status[]=b`.
 */
  'status[]'?: Array<string>;
  contractor_phone?: string;
  contractor_siren?: string;
  mission_ref?: string;
  min_amount?: number;
  max_amount?: number;
  date_from?: string;
  date_to?: string;
  validator_missing?: 'compliance' | 'production' | 'accounting';

/**
 * Nombre de validations manquantes (0 à 3). 3 = aucune approbation.
 */
  missing_approvals?: number;

/**
 * Ancienneté minimale en jours sur le statut courant.
 */
  pending_since?: number;
  plan?: 'free' | 'pro';
  paid_disputed?: boolean;

/**
 * Factures avec une cause de blocage métier (failure_reason ou statut rejeté).
 */
  blocked?: boolean;

/**
 * Onglet « À valider » en file par admin : exclut les factures sur lesquelles l'admin courant a déjà voté (approve ou reject). L'identité de l'admin est résolue côté backend via le Bearer OAuth2.
 */
  exclude_self_validated?: boolean;
}

export function adminInvoicesList(http: HttpClient, rootUrl: string, params?: AdminInvoicesList$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminInvoicesList.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('stuck', params.stuck, {});
    rb.query('page', params.page, {});
    rb.query('per_page', params.per_page, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
    rb.query('q', params.q, {});
    rb.query('status[]', params['status[]'], {});
    rb.query('contractor_phone', params.contractor_phone, {});
    rb.query('contractor_siren', params.contractor_siren, {});
    rb.query('mission_ref', params.mission_ref, {});
    rb.query('min_amount', params.min_amount, {});
    rb.query('max_amount', params.max_amount, {});
    rb.query('date_from', params.date_from, {});
    rb.query('date_to', params.date_to, {});
    rb.query('validator_missing', params.validator_missing, {});
    rb.query('missing_approvals', params.missing_approvals, {});
    rb.query('pending_since', params.pending_since, {});
    rb.query('plan', params.plan, {});
    rb.query('paid_disputed', params.paid_disputed, {});
    rb.query('blocked', params.blocked, {});
    rb.query('exclude_self_validated', params.exclude_self_validated, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminInvoicesList.PATH = '/contractor-compliance/admin/invoices';
