/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminInvoicesMarkPaid$Params {
  uuid: string;
      body: {

/**
 * Référence virement bancaire (obligatoire, masquée en logs).
 */
'payment_ref': string;

/**
 * Date de paiement effective (ISO 8601). Défaut = maintenant.
 */
'paid_at'?: string;

/**
 * Bag opaque transmis au MarkPaidService (chemins accélérés).
 */
'fast_path'?: {
[key: string]: any;
};
}
}

export function adminInvoicesMarkPaid(http: HttpClient, rootUrl: string, params: AdminInvoicesMarkPaid$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminInvoicesMarkPaid.PATH, 'post');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminInvoicesMarkPaid.PATH = '/contractor-compliance/admin/invoices/{uuid}/mark-paid';
