/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminInvoicesValidate$Params {
  uuid: string;
      body: {
'decision': 'approved' | 'rejected';
'admin_email': string;

/**
 * Code de motif structuré (préférence sur `reason`).
 */
'reason_code'?: string;

/**
 * Motif texte libre (fallback de `reason_code`).
 */
'reason'?: string;

/**
 * ID de corrélation (généré si absent).
 */
'correlation_id'?: string;
}
}

export function adminInvoicesValidate(http: HttpClient, rootUrl: string, params: AdminInvoicesValidate$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminInvoicesValidate.PATH, 'post');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminInvoicesValidate.PATH = '/contractor-compliance/admin/invoices/{uuid}/validate';
