/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminInvoicesResolveDispute$Params {
  uuid: string;
      body: {

/**
 * Décision comptable retenue pour clôturer le litige.
 */
'resolution': 'credit_note_issued' | 'amicable_refund' | 'no_action';

/**
 * Justification comptable du règlement (20 caractères minimum). Consignée dans l'audit trail — l'URSSAF peut en demander le détail.
 */
'notes': string;
}
}

export function adminInvoicesResolveDispute(http: HttpClient, rootUrl: string, params: AdminInvoicesResolveDispute$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminInvoicesResolveDispute.PATH, 'post');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminInvoicesResolveDispute.PATH = '/contractor-compliance/admin/invoices/{uuid}/resolve-dispute';
