/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminInvoicesForceResendWebhook$Params {
  uuid: string;
      body: {

/**
 * Nom de l'event à re-émettre (une seule famille par appel).
 */
'event': 'rejected' | 'ready_to_pay' | 'payment_in_progress' | 'paid' | 'reopened' | 'cancelled';
}
}

export function adminInvoicesForceResendWebhook(http: HttpClient, rootUrl: string, params: AdminInvoicesForceResendWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminInvoicesForceResendWebhook.PATH, 'post');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminInvoicesForceResendWebhook.PATH = '/contractor-compliance/admin/invoices/{uuid}/force-resend-webhook';
