/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminInvoicesMarkPaymentInProgress$Params {
  uuid: string;
      body?: {

/**
 * Identité de l'admin actant la transition (fallback :
 * identité OAuth2 du bearer). Tracé dans la timeline
 * + audit log.
 */
'admin_email'?: string;
}
}

export function adminInvoicesMarkPaymentInProgress(http: HttpClient, rootUrl: string, params: AdminInvoicesMarkPaymentInProgress$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminInvoicesMarkPaymentInProgress.PATH, 'post');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminInvoicesMarkPaymentInProgress.PATH = '/contractor-compliance/admin/invoices/{uuid}/mark-payment-in-progress';
