/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JsonObject } from '../../models/json-object';
import { SuccessEnvelope } from '../../models/success-envelope';

export interface AdminFreeInvoicesApprove$Params {
  uuid: string;
      body: JsonObject
}

export function adminFreeInvoicesApprove(http: HttpClient, rootUrl: string, params: AdminFreeInvoicesApprove$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessEnvelope>> {
  const rb = new RequestBuilder(rootUrl, adminFreeInvoicesApprove.PATH, 'post');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessEnvelope>;
    })
  );
}

adminFreeInvoicesApprove.PATH = '/contractor-compliance/admin/free-invoices/{uuid}/approve';
