/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AdminPurchasesExport$Params {
  status?: string;
  document_type?: string;

/**
 * Borne basse de période (YYYY-MM-DD).
 */
  since?: string;

/**
 * Borne haute de période (YYYY-MM-DD).
 */
  until?: string;
}

export function adminPurchasesExport(http: HttpClient, rootUrl: string, params?: AdminPurchasesExport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, adminPurchasesExport.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('document_type', params.document_type, {});
    rb.query('since', params.since, {});
    rb.query('until', params.until, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'text/csv', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

adminPurchasesExport.PATH = '/contractor-compliance/admin/purchases/export';
